name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - run: |
        sudo add-apt-repository -y ppa:alexlarsson/flatpak
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libostree-dev libselinux1-dev libdevmapper-dev
    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    # - name: Install dependencies
    #   run: |
    #     go mod download
    # - run: mv $GOPATH/src/github.com/StarOfService $GOPATH/src/github.com/starofservice
    - name: Run Unit tests
      run: |
        sudo ./hack/travis-test.sh
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
    # or use shogo82148/actions-goveralls
    # - name: Send coverage
    #   uses: shogo82148/actions-goveralls@v1
    #   with:
    #     path-to-profile: covprofile